a = {
    0: {
        "encoded": [
            "be",
            "cfbegad",
            "cbdgef",
            "fgaecd",
            "cgeb",
            "fdcge",
            "agebfd",
            "fecdb",
            "fabcd",
            "edb",
        ],
        "output": ["fdgacbe", "cefdb", "cefbgd", "gcbe"],
    },
    1: {
        "encoded": [
            "edbfga",
            "begcd",
            "cbg",
            "gc",
            "gcadebf",
            "fbgde",
            "acbgfd",
            "abcde",
            "gfcbed",
            "gfec",
        ],
        "output": ["fcgedb", "cgb", "dgebacf", "gc"],
    },
    2: {
        "encoded": [
            "fgaebd",
            "cg",
            "bdaec",
            "gdafb",
            "agbcfd",
            "gdcbef",
            "bgcad",
            "gfac",
            "gcb",
            "cdgabef",
        ],
        "output": ["cg", "cg", "fdcagb", "cbg"],
    },
    3: {
        "encoded": [
            "fbegcd",
            "cbd",
            "adcefb",
            "dageb",
            "afcb",
            "bc",
            "aefdc",
            "ecdab",
            "fgdeca",
            "fcdbega",
        ],
        "output": ["efabcd", "cedba", "gadfec", "cb"],
    },
    4: {
        "encoded": [
            "aecbfdg",
            "fbg",
            "gf",
            "bafeg",
            "dbefa",
            "fcge",
            "gcbea",
            "fcaegb",
            "dgceab",
            "fcbdga",
        ],
        "output": ["gecf", "egdcabf", "bgf", "bfgea"],
    },
    5: {
        "encoded": [
            "fgeab",
            "ca",
            "afcebg",
            "bdacfeg",
            "cfaedg",
            "gcfdb",
            "baec",
            "bfadeg",
            "bafgc",
            "acf",
        ],
        "output": ["gebdcfa", "ecba", "ca", "fadegcb"],
    },
    6: {
        "encoded": [
            "dbcfg",
            "fgd",
            "bdegcaf",
            "fgec",
            "aegbdf",
            "ecdfab",
            "fbedc",
            "dacgb",
            "gdcebf",
            "gf",
        ],
        "output": ["cefg", "dcbef", "fcge", "gbcadfe"],
    },
    7: {
        "encoded": [
            "bdfegc",
            "cbegaf",
            "gecbf",
            "dfcage",
            "bdacg",
            "ed",
            "bedf",
            "ced",
            "adcbefg",
            "gebcd",
        ],
        "output": ["ed", "bcgafe", "cdgba", "cbgef"],
    },
    8: {
        "encoded": [
            "egadfb",
            "cdbfeg",
            "cegd",
            "fecab",
            "cgb",
            "gbdefca",
            "cg",
            "fgcdab",
            "egfdb",
            "bfceg",
        ],
        "output": ["gbdfcae", "bgc", "cg", "cgb"],
    },
    9: {
        "encoded": [
            "gcafb",
            "gcf",
            "dcaebfg",
            "ecagb",
            "gf",
            "abcdeg",
            "gaef",
            "cafbge",
            "fdbac",
            "fegbdc",
        ],
        "output": ["fgae", "cfgab", "fg", "bagce"],
    },
}
